# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
#use_frameworks!
target 'RCTTest' do
source 'https://github.com/CocoaPods/Specs.git'

   # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
      'RCTText',
      'RCTImage',
      'RCTNetwork',
      'RCTWebSocket', 
      # 这个模块是用于调试功能的
      # 在这里继续添加你所需要的模块
    ]
    # 如果你的RN版本 >= 0.42.0，请加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod "MJExtension"
    pod "MJRefresh"
    pod "AFNetworking"
    pod "SDWebImage"
    pod 'IconFont'
end
